### ISSUE TITLE
std::string versus String for response->print()

### ISSUE THREAD

**Issue by frankcohen** [fhessel/esp32_https_server#128]
Great job writing this library! It's helped me so much.

I wrote a handler as:

void handle_getpassword(HTTPRequest * req, HTTPResponse * res){
  ...
  std::string ssid;
  req->getParams()->getQueryParameter("ssid", ssid);  
  ...
  res->print( ssid );
  ...
}

I get a compile time error:

/Users/frankcohen/Documents/Arduino/EleksHack/EleksHack.ino: In function 'void handle_getpassword(httpsserver::HTTPRequest*, httpsserver::HTTPResponse*)':
EleksHack:497:20: error: no matching function for call to 'httpsserver::HTTPResponse::print(std::__cxx11::string&)'
   res->print( ssid );

Seems like there is no print method that takes the C++ std:string. It works with a String value.

What should I do?

-Frank

**Comment by amandel** [comment]
try `res->print( ssid.c_str() );`

**Comment by frankcohen** [comment]
That works. Thank you. -Frank

**Comment by kinafu** [comment]
@frankcohen you might want to mark this issue as "closed" 😊
