### ISSUE TITLE
"HTTPRequest::getHeader" bug when "name" not found

### ISSUE THREAD

**Issue by BojanJurca** [fhessel/esp32_https_server#14]
Hi, Frank. First of all, I would like to thank you - your https server is really a great job. I'm dealing with adding http functionality right now for my home project and have just found a minor error in HTTPRequest::getHeader. "return NULL;" in case std::string name can not be found causes "Fatal C ++: basic_string::_ M_construct null is invalid" and must be "return std::string ();"; instead. Bojan

**Comment by fhessel** [comment]
Hi Bojan,
thank your for the feedback, that was indeed an error that my compiler did just handle gracefully.
I created [a pull request](https://github.com/fhessel/esp32_https_server/pull/16) and checked for similar errors in the rest of the code (I did not find any, though). Would you have a short look at it and check if that's all you need? Then I'll merge it back to master.
Best,
Frank
