### ISSUE TITLE
Debug Messages

### ISSUE THREAD

**Issue by dorarosi** [fhessel/esp32_https_server#27]
How can I disable the Debug Messages?

**Software**
 - IDE and Version: Arduino 1.8.7
 - OS: Windows 10

**Comment by fhessel** [comment]
At the moment, the only way to achieve that is to edit [HTTPSServerConstants.hpp](https://github.com/fhessel/esp32_https_server/blob/master/src/HTTPSServerConstants.hpp).

The following lines...
```c++
#define HTTPS_DLOG(X)      Serial.print(millis());Serial.print(" HTTPSServer->debug: ");Serial.println(X);
#define HTTPS_DLOGHEX(X,Y) Serial.print(millis());Serial.print(" HTTPSServer->debug: ");Serial.print(X);Serial.print(" 0x");Serial.println(Y, HEX);
#define HTTPS_DLOGINT(X,Y) Serial.print(millis());Serial.print(" HTTPSServer->debug: ");Serial.print(X);Serial.println(Y);
```

...have to be replaced by this:
```c++
#define HTTPS_DLOG(X)
#define HTTPS_DLOGHEX(X,Y)
#define HTTPS_DLOGINT(X,Y)
```

Using `#undef HTTPS_DLOG` or something similar in your Sketch won't work, as the IDE compiles libraries and your sketch separately. On long-term basis, it might be the best option to migrate to the default logging functions of the ESP32, I have that on my to do list.
