### ISSUE TITLE
For POST requests discardRequestBody causes infinite loop

### ISSUE THREAD

**Issue by roger-zacharczyk** [fhessel/esp32_https_server#28]
Also, calling my method

void consumeRequestBody(httpsserver::HTTPRequest *request) {
  byte buffer[10];
  while (!request->requestComplete()) {
    DEBUG_LOG(request->getContentLength());
    request->readBytes(buffer, 10);
  }
}

Seems to not decrease the remaining length.

For:
curl -X POST https://host/dest -d par=val -d par2=val2

**Comment by fhessel** [comment]
Thank you for the report, I assume that I made a mistake during a merge of a pull request. Please try again with the current master branch.
