### ISSUE TITLE
Crash while close WebSocket Handler

### ISSUE THREAD

**Issue by RezaGolriz** [fhessel/esp32_https_server#44]
**Describe the bug**
I've find out while using WebSocket handler a crash will happen if try to stop the server. I've found out that this caused by not setting the _wsHandler to null in the HTTP Connection::closeConnection() method

**Comment by fhessel** [comment]
Thanks for the report.

WebSockets are still not fully supported, so there may be a variety of bugs.

I currently don't have the time to investigate this in-depth, but if you want a quick fix in the master, feel free to open a PR, ideally with a minimal (non-)working example to verify that easily. Sounds like you tracked down the problem quite well already.
