### ISSUE TITLE
HTTPConnection.cpp _sockAddr public access

### ISSUE THREAD

**Issue by f34rdotcom** [fhessel/esp32_https_server#70]
I want to get access to the IP address for ACL control by address as well as reporting.
Is this possible? I could not find any method so far.

**Comment by fhessel** [comment]
You're right, that field was internal (and not populated correctly) by now.

Would #71 work for you? I went for returning an `IPAddress` as handling the `sockaddr` might be a bit too complicated in the Arduino context.

Also, it's IPv4 only at the moment, but I'd have to check some other parts as well to get IPv6 working properly.

**Comment by f34rdotcom** [comment]
Works perfect thanks! Not worried about ipv6... yet...

Thanks again!
