### ISSUE TITLE
Request Header Fields Too Large

### ISSUE THREAD

**Issue by Leon12345679** [fhessel/esp32_https_server#80]
I'm using the ESP32-WROOM and developing with the Arduino IDE.
I noticed that there is a hard 128 character param size limit. How can I remove this?

**Comment by pargall** [comment]
The 128 character limit is configured here:
https://github.com/fhessel/esp32_https_server/blob/daf6ca1c4359e9c9fdea561a748ebc8be029fb23/src/HTTPSServerConstants.hpp#L54

You can override it at compile time by defining your own constant (before including the other .hpp).  
Something like:
````C 
#define HTTPS_REQUEST_MAX_REQUEST_LENGTH 512
#include <HTTPSServer.hpp>
#include <SSLCert.hpp>
#include <HTTPRequest.hpp>
#include <HTTPResponse.hpp>
````
